root = "."
tmp_dir = "tmp"

[build]
  bin = "./bin/orders"
  cmd = "task unit-test && task docs && task build"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "terraform", "bin"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "30s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
