version: "3.8"

# Default service build args
x-build:
  &default-build
  context: .
  dockerfile: Dockerfile
  args:
    APP_NAME: ${APP_NAME}
    ECR_HOST: ${ECR_HOST}
    GIT_HASH: ${GIT_HASH}

#default application runtime vars
x-app-vars:
  &default-app-vars
  ENVIRONMENT: development
  PORT: 8080

services:
  orders:
    image: ${ECR_HOST}/drizlyinc/${APP_NAME}/development:${TAG:-local}
    build:
      << : *default-build
      target: development
    environment: 
      << : *default-app-vars
    ports:
      - "8080:8080"
    volumes:
      - .:/build
      - /build/bin/

  orders-prod:
    profiles:
      - production
    image: ${ECR_HOST}/drizlyinc/${APP_NAME}/production:${TAG:-local}
    build:
      << : *default-build
      target: production
    environment: 
      << : *default-app-vars
      ENVIRONMENT: production
    ports:
      - "8081:8080"
